# Numpy

파이썬의 패키지 ```NumPy```는 선형 대수에 필요한 모든 기능들을 갖추고 있다.

## ```array```

```Numpy``` 패키지를 import 함으로써, ```ndarray```라 불리우는 데이터타입을 이용할 수 있다. 

보통 ```import numpy as np```로 ```Numpy``` 패키지를 import를 하여 사용한다.  
이 경우에는 Numpy 패키지에서 정의된 함수나 상수들을 사용할 때, ```np.```을 붙여야 한다.  

In [1]:
import numpy as np

### Vector와 matrix

수학적 대상인 vector는 ```array```로 쉽게 표현된다.  
만약 ```import numpy as np```로 import 하였으면 ```np.array```로 표현한다.

In [2]:
v = np.array([1.,2.,3.])
v

array([1., 2., 3.])

각종 vector 관련 수학적 연산을 수행할 수 있다.

In [3]:
# two vectors with three components
v1 = np.array([1., 2., 3.])
v2 = np.array([2, 0, 1.])

In [4]:
# scalar multiplication
2 * v1 

array([2., 4., 6.])

In [5]:
# scalar division
v1 / 2 

array([0.5, 1. , 1.5])

In [6]:
# 선형 조합
3*v1 + 2*v2

array([ 7.,  6., 11.])

추가적으로 ```numpy.linalg``` module을 import 함으로써, Euclidean norm (L2 norm) - 원점으로부터의 거리를 계산할 수 있다.

```numpy.linalg```는 numpy의 submodule로 선형 대수와 관련된 각종 함수들이 구현되어 있다.

In [7]:
# norm
from numpy.linalg import norm
norm(v1) 

3.7416573867739413

다음으로 정의되는 dot product의 연산 또한 가능하다.

$$ a \cdot b = \sum_{i=1}^{n} a_i b_i $$

In [8]:
np.dot(v1, v2)

5.0

In [9]:
# 또다른 방법
v1 @ v2

5.0

산술 연산은 모두 elementwise 방식으로 이루어진다.

In [10]:
v1 * v2

array([2., 0., 3.])

In [11]:
v2 / v1

array([2.        , 0.        , 0.33333333])

In [12]:
v1 - v2

array([-1.,  2.,  2.])

In [13]:
v1 + v2

array([3., 2., 4.])

```Numpy```에서 정의된 일부 함수들 또한 elementwise 방식으로 계산된다.

In [14]:
np.cos(v1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

Matrix는 vector와 비슷하게 ```array```를 이용하여 정의할 수 있다.

In [15]:
M = np.array([[1., 2.], [0., 1.]])
M

array([[1., 2.],
       [0., 1.]])

수학적으로 vector는 column matrix나 row matrix로 간주될 수 있지만, ```Numpy```에서는 길이 $n$의 벡터와 $n\times1$ 혹은 $1\times n$의 행렬은 구분된다.

```reshape```을 이용하여, vector를 행렬로 바꿀 수 있다. ```reshape```은 데이터의 차원을 바꿀 때 종종 활용된다.

In [16]:
v = np.array([1., 2., 1.])
v

array([1., 2., 1.])

$1 \times 3$의 행렬

In [17]:
R = v.reshape((1,3))
R

array([[1., 2., 1.]])

In [18]:
np.shape(v)

(3,)

In [19]:
np.shape(R)

(1, 3)

In [20]:
v.shape

(3,)

In [21]:
R.shape

(1, 3)

$3\times 1$의 행렬

In [22]:
C = v.reshape((3, 1))
C

array([[1.],
       [2.],
       [1.]])

In [23]:
np.shape(C)

(3, 1)

###  Indexing and slices

Indexing과 slice는 ```array```의 일부 원소를 선택할 때 활용한다.

In [24]:
v = np.array([1., 2., 3])
M = np.array([[1., 2],[3., 4]])

In [25]:
v[0]

1.0

In [26]:
v[1:]

array([2., 3.])

In [27]:
M[0, 0]

1.0

다음의 결과는 여전히 행렬이다.

In [28]:
M[1:]

array([[3., 4.]])

다음의 결과는 vector이다.

In [29]:
M[1]

array([3., 4.])

In [30]:
v[0] = 10
v

array([10.,  2.,  3.])

In [31]:
v[:2] = [0, 1]
v

array([0., 1., 3.])

### 선형 대수 연산

기본적으로 ```dot``` 함수와 이항 연산자 ```@```를 이용한 연산을 살펴본다.

In [32]:
v = np.array([1., 2.])
M = np.array([[1., 2],[3., 4]])

행렬과 벡터 간에 ```dot``` 혹은 ```@```를 이용하면 행렬과 벡터의 곱이다.

In [33]:
np.dot(M, v)

array([ 5., 11.])

In [34]:
M @ v

array([ 5., 11.])

벡터 간에 ```dot``` 혹은 ```@```를 이용하면 dot product이다.

In [35]:
w = np.array([4., 5.])
np.dot(v, w) 

14.0

In [36]:
v @ w

14.0

행렬 간에 ```dot``` 혹은 ```@```를 이용하면 행렬과 행렬의 곱이다.

In [37]:
N = np.array([[2., 1],[4., 3]])
np.dot(M, N)

array([[10.,  7.],
       [22., 15.]])

In [38]:
M @ N

array([[10.,  7.],
       [22., 15.]])

선형 연립 방정식 풀이는 ```numpy.linalg```의 ```solve```함수를 이용한다.

즉, 행렬 $A$와 벡터 $b$로 이루어진 다음의 선형 시스템에서 $x$를 구한다.
$$ Ax = b $$
예를 들어,
$$ 
 \left\{\begin{array}{lr}
        x_1 + 2 x_2  & = 1\\
        3x_1 + 4 x_2 & = 4\\
        \end{array}\right.
$$
를 풀어 보자.

In [39]:
from numpy.linalg import solve
A = np.array([[1., 2.], [3., 4.]])
b = np.array([1., 4.])
x = solve(A, b)
x

array([ 2. , -0.5])

```allclose```를 이용하여 정답인지 확인해 보자.
```allclose```는 두 값이 서로 (거의) 같다면 ```True```를 반환한다.

In [40]:
np.allclose(np.dot(A, x), b)

True

In [41]:
np.allclose(A @ x, b)

True

### Array type

```array```의 세가지 주요 attributes는 다음과 같다.


| 이름 | 설명 |  
|:------|:---|
| shape | dimension을 설명하는 속성 |  
| dtype | data의 type을 설명 (float, complex, integer 등) |  
| strides | 메모리 상에서 다음 행이나 열로 이동할 때, 건너 뛰어야 하는 byte의 수 |

In [42]:
A = np.array([[1, 2, 3], [3, 4, 6]])
A.shape   # (2, 3)

(2, 3)

In [43]:
A.dtype

dtype('int32')

In [44]:
A.strides 

(12, 4)

In [45]:
A[:,::2].strides

(12, 8)

### list로부터 array생성

```array```를 생성하는 가장 간단한 방법은 python list를 이용하는 것이다.

In [46]:
V = np.array([1., 2., 1.], dtype=float)
V

array([1., 2., 1.])

In [47]:
V = np.array([1., 2., 1.], dtype=complex)
V

array([1.+0.j, 2.+0.j, 1.+0.j])

In [48]:
V = np.array([1, 2]) # [1, 2] is a list of integers
V.dtype 

dtype('int32')

In [49]:
V = np.array([1., 2]) # [1., 2] mix float/integer
V.dtype

dtype('float64')

In [50]:
V = np.array([1. + 0j, 2.]) # mix float/complex
V.dtype

dtype('complex128')

In [51]:
Id = np.array([[1., 0.],
            [0., 1.]])

Id

array([[1., 0.],
       [0., 1.]])

### 행렬 원소 접근

가장 기본적인 방법은 행과 열의 index 번호를 순차적으로 이용하는 것이다.

In [52]:
M = np.array([[1., 2.],[3., 4.]])
M[0, 0] # first row, first column: 1.0

1.0

In [53]:
M[-1, 0] # last row, first column: 3.0

3.0

slicing(```:```)을 이용하면 여러 개의 원소를 선택할 수 있다.

* ```M[i, :]``` : i번째 행 벡터  
* ```M[:, j]``` : j번째 열 벡터
* ```M[a:b, :]``` : 행을 ```a:b```로 slicing한 행렬
* ```M[a:b, c:d]``` : 행을 ```a:b```로, 열을 ```c:d```로 slicing한 행렬

정리하면 다음과 같다.

| Access | ndim | 종류 |
|:--:|:--:|:--:|
index,index | 0 | 스칼라 |
slice,index | 1 | 벡터 |
index,slice | 1 | 벡터 |
slice,slice | 2 | 행렬 |

slicing된 array의 원소를 변경하면 원래의 array도 변경된다.

In [54]:
v = np.array([1., 2., 3.])
v1 = v[:2] # v1 is array([1., 2.])
v1[0] = 0. # if v1 is changed ...
v # ... v is changed too: array([0., 2., 3.])

array([0., 2., 3.])

### Indexing과 slicing을 이용한 변경

In [55]:
M = np.zeros((5,3))
M[1, 2] = 2.0 # scalar
M

array([[0., 0., 0.],
       [0., 0., 2.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
M[2, :] = [1., 2., 3.] # vector
M

array([[0., 0., 0.],
       [0., 0., 2.],
       [1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
M[1:3, :] = np.array([[1., 2., 3.],[-1.,-2., -3.]])
M

array([[ 0.,  0.,  0.],
       [ 1.,  2.,  3.],
       [-1., -2., -3.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [58]:
M[1:4, 1:2] = np.array([[1.],[0.],[-1.0]]) 
M

array([[ 0.,  0.,  0.],
       [ 1.,  1.,  3.],
       [-1.,  0., -3.],
       [ 0., -1.,  0.],
       [ 0.,  0.,  0.]])

### Array를 생성하는 다양한 함수

| 함수 | shape | 반환 |
|:--|:--|:--|
|```identity(n)``` | (n,n) | 단위 행렬 |
|```zeros((n,m))``` | (n,m) |  0으로 채워진 행렬 |
|```ones((n,m))``` | (n,m) | 1로 채워진 행렬 |
|```full((n,m), q)``` | (n,m) | ```q```로 채워진 행렬 |
|```diag(v, k)``` | (n,n) | ```v```로 이루어진 대각행렬, ```k```(정수)를 이용하여 대각의 위치 조정 |
|```random.random(n,m)``` | (n,m) | (0,1) 사이에서 균등 분포를 따르는 랜덤 숫자로 이루어진 행렬 |
|```arange(n)``` | (n,) | 0부터 n-1까지의 정수로 이루어진 벡터 |
|```linspace(a,b,n)``` | (n,) | a와 b사이의 n개의 등거리로 나누어진 값들로 이루어진 벡터 |

In [59]:
np.diag([1,2,3], k = 2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### ```shape``` as a function

In [60]:
M = np.identity(3)
np.shape(M) 

(3, 3)

In [61]:
M.shape

(3, 3)

In [62]:
np.shape(1.) 

()

In [63]:
np.shape([1,2]) 

(2,)

In [64]:
np.shape([[1,2]])

(1, 2)

### ```ndim```: attribute and function

In [65]:
v

array([0., 2., 3.])

In [66]:
np.ndim(v)

1

In [67]:
v.ndim

1

In [68]:
A

array([[1, 2, 3],
       [3, 4, 6]])

In [69]:
np.ndim(A) # 2

2

In [70]:
A.ndim # 2

2

In [71]:
T = np.zeros((2,2,3)) # tensor of shape (2,2,3); three dimensions
np.ndim(T) # 3

3

In [72]:
len(np.shape(T)) # 3

3

### Reshape

Array의 형태를 변경하기 위해 ```reshape``` method가 종종 활용된다.

In [73]:
v = np.array([0,1,2,3,4,5])
M = v.reshape(2,3)
M

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
np.shape(M) # returns (2,3)

(2, 3)

slicing처럼 reshape은 새로운 array를 생성하는 것이 아니다.

기존의 array에 view를 제공하는 것이다.

따라서, reshape된 object를 변경하면 원래의 array도 변경된다.

In [75]:
M[0,0] = 10 # now v[0] is 10
v

array([10,  1,  2,  3,  4,  5])

reshape을 할 때, 새로운 행과 열의 수를 모두 계산할 필요없이, 열과 행 중 어느 하나의 shape parameter를 정해주고, 남은 parameter는 python에서 자동으로 결정하게 하는 것도 좋은 방법이다.

Python에서 자동으로 정하게 할 때 ```-1```을 인자로 사용한다.

In [76]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8])
M = v.reshape(2, -1)
M

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

행렬의 transpose는 ```.T```를 이용한다.

Reshape과 마찬가지로, transpose 또한 새로운 행렬을 생성하는 것이 아니다.

In [77]:
A = np.ones((3,4))
B = A.T
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
A= np.array([[ 1., 2.],[ 3., 4.]]) 
B = A.T 
A[1,1]=5. 
B

array([[1., 3.],
       [2., 5.]])

벡터의 transpose는 원래의 값과 동일하다.

In [79]:
v = np.array([1., 2., 3.])
v.T

array([1., 2., 3.])

vector를 $n \times 1$ 행렬이나, $1 \times n$ 행렬로 바꿀 때에도, reshape이 이용된다.

In [80]:
v.reshape(-1, 1) # column matrix containing v

array([[1.],
       [2.],
       [3.]])

In [81]:
v.reshape(1, -1) # row matrix containing v

array([[1., 2., 3.]])

Numpy의 ```ravel``` 함수는 혹은 array 메소드는 해당 array의 모든 차원을 없애 일차원 array로 바꾼 view를 제공한다.  
비슷하게 ```flatten```도 사용할 수 있으며, 이 때는 copy를 제공한다. 

In [82]:
A.ravel()

array([1., 2., 3., 5.])

In [83]:
A.flatten()

array([1., 2., 3., 5.])

### Stacking

여러 행렬을 겹쳐 쌓아 새로운 행렬을 만들 때 ```concatenate```함수가 이용된다. ```axis```를 조정하여 어떤 방향으로 쌓을지 정한다.

In [84]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [86]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

다음의 변형된 함수들 또한 자주 이용된다.

* ```hstack``` :  수평 방향   
* ```vstack``` :  수직 방형   
* ```column_stack``` :  컬럼들로 

In [87]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [88]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

### Universal function

Array의 원소별로 적용되는 함수를 universal function이라 한다.

In [91]:
np.cos(np.pi)

-1.0

In [92]:
np.cos(np.array([[0, np.pi/2, np.pi]]))

array([[ 1.000000e+00,  6.123234e-17, -1.000000e+00]])

numpy universal functions :

```numpy.cos, numpy.sin, numpy.tan```  
```numpy.arcos, numpy.arcsin, numpy.arctan```  
```numpy.cosh, numpy.sinh, numpy.tanh```  
```numpy.arccosh, numpy.arcsinh, numpy.arctanh```   
```numpy.sqrt```  
```numpy.exp```  
```numpy.log, numpy.log2, numpy.log10```

Universal function 만들기

아래의 ```heaviside``` 함수는 universal function이 아니다.

In [93]:
def heaviside(x):
    if x >= 0:
        return 1.
    else: 
        return 0.

```vectorize```함수를 통해 universal function으로 만들 수 있다.

In [94]:
vheaviside = np.vectorize(heaviside)

In [95]:
vheaviside(np.array([-1, 2]))

array([0., 1.])

### Array functions

In [96]:
A = np.arange(1,9).reshape(2,-1)
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
np.sum(A)

36

In [98]:
np.sum(A, axis=0)

array([ 6,  8, 10, 12])

In [99]:
np.sum(A, axis=1)

array([10, 26])

In [100]:
A.sum(axis=1)

array([10, 26])

### Array view와 copy

Numpy는 보다 효율적인 메모리 관리를 위해 view라는 개념을 제공한다.
View는 보다 큰 array의 data를 공유하는 작은 array라고 생각할 수 있다.  
앞에서 언급한 것처럼 slicing은 view를 이용한다.

In [101]:
M = np.array([[1.,2.],[3.,4.]])
v = M[0,:] # first row of M

In [102]:
v[-1] = 0.
v

array([1., 0.])

In [103]:
M

array([[1., 0.],
       [3., 4.]])

In [104]:
v.base

array([[1., 0.],
       [3., 4.]])

In [105]:
v.base is M

True

In [106]:
print(M.base)

None


Slicing을 통한 selection만이 view를 생성하며, boolean이나 정수 index를 이용한 선택은 copy를 생성한다.

In [107]:
a = np.arange(4) 
b = a[[2,3]] 
b # view가 아니다

array([2, 3])

In [108]:
b.base is None

True

In [109]:
c = a[1:3] 
c.base is a

True

그 외에 reshape과 transpose는 view를 생성한다.

In [110]:
M = np.random.random_sample((3,3))
N = M.T
N.base is M 

True

In [111]:
v = np.arange(10)
C = v.reshape(-1,1) # column matrix
C.base is v

True

데이터를 복사할 필요가 있을 때는 복사하여 사용한다.

In [112]:
M = np.array([[1.,2.],[3.,4.]])
N = np.array(M.T)

In [113]:
N.base is None

True

```copy``` method를 이용할 수 있다.

In [114]:
N2 = M.T.copy()

In [115]:
N2.base is None

True

### Boolean array

In [116]:
A = np.array([True,False]) # Boolean array
A.dtype 

dtype('bool')

In [117]:
M = np.array([[2, 3],
           [1, 4]])
M > 2

array([[False,  True],
       [False,  True]])

In [118]:
M == 0

array([[False, False],
       [False, False]])

In [119]:
N = np.array([[2, 3],
           [0, 0]])
M == N

array([[ True,  True],
       [False, False]])

In [120]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,3]])
A == B 

array([[ True,  True],
       [ True, False]])

* ```numpy.all``` : 모든 원소가 True인지 테스트  
* ```numpy.any``` : 어느 하나의 원소라도 True인지 테스트

In [121]:
(A == B).all()

False

In [122]:
(A != B).any()

True

In [123]:
if (abs(B-A) < 1e-10).all():
    print("The two arrays are close enough")

실수로 구성된 두 array를 비교하는 것은 쉬운 것은 아니다.
Numpy에선 ```allclose```를 통하여, 비교하도록 되어있다.

In [124]:
data = np.random.rand(2)*1e-3
small_error = np.random.rand(2)*1e-16
data == data + small_error

array([False, False])

```rtol```는 relative tolerance bound, ```atol```는 absoulte error bound를 의미

In [125]:
np.allclose(data, data + small_error, rtol=1.e-5, atol=1.e-8)

True

Numpy array를 대상으로 boolean operation을 진행할 때, ```and```, ```or```, ```not```을 사용하지 않는다.  
대신 comonentwise operator로 ```&, |, ~```를 사용한다.

In [126]:
A = np.array([True, True, False, False])
B = np.array([True, False, True, False])

In [127]:
A & B

array([ True, False, False, False])

In [128]:
A | B

array([ True,  True,  True, False])

In [129]:
~A

array([False, False,  True,  True])

### Array indexing

Slicing 외에도 정수나 boolean array를 이용하여 indexing을 할 수 있다.  
먼저 boolean indexing을 살펴보는데, 결과가 벡터가 됨을 유의해서 살펴보라.

In [130]:
B = np.array([[True, False],
           [False, True]])
M = np.array([[2, 3],
           [1, 4]])
M[B]

array([2, 4])

In [131]:
M[B] = 0
M

array([[0, 3],
       [1, 0]])

In [132]:
M[B] = 10, 20
M

array([[10,  3],
       [ 1, 20]])

In [133]:
M[M>2] = 0    # all the elements > 2 are replaced by 0
M

array([[0, 0],
       [1, 0]])

```where```는 특정 조건을 만족하는 원소들의 위치를 특정하는데 편리하다. 기본 용법은 다음과 같다.  

```where(conition, a, b)```  

```condition```이 True인 곳은 ```a```를, False인 곳은 ```b```를 반환한다.

In [134]:
def H(x):
    return np.where(x < 0, 0, 1)
x = np.linspace(-1,1,11)  # [-1. -0.8 -0.6 -0.4 -0.2 0. 0.2 0.4 0.6 0.8 1. ]
print(H(x)) 

[0 0 0 0 0 1 1 1 1 1 1]


In [135]:
x = np.linspace(-4,4,5)
print(x)

[-4. -2.  0.  2.  4.]


In [136]:
print(np.where(x < 0, -x, x))

[4. 2. 0. 2. 4.]


In [137]:
print(np.where(x > 0, 1, -1)) # [-1 -1 -1  1  1]

[-1 -1 -1  1  1]


만약 ```where```의 두번째, 세번째 인자가 생략되면, ```condition```이 True인 위치의 index들이 반환된다.

In [138]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [139]:
b = a.reshape((3,3))
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [140]:
np.where(a > 5)

(array([6, 7, 8], dtype=int64),)

In [141]:
np.where(b > 5)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

### Set operation

Numpy array는 집합을 표현하는 데에 사용할 수 있다.  


In [142]:
a = np.unique([1,2,3,3])
a

array([1, 2, 3])

In [143]:
b = np.unique([2,3,4,4,5,6,5])
b

array([2, 3, 4, 5, 6])

```np.in1d```는 원소가 속해있는지 여부를 확인한다.

In [144]:
np.in1d(a, b)

array([False,  True,  True])

In [145]:
1 in a

True

In [146]:
1 in b

False

부분 집합의 여부는 다음과 같이 확인 가능 하다.

In [147]:
np.all(np.in1d(a, b))

False

그 외에 합집합, 교집합, 차집합 등의 연산이 가능하다.

In [148]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [149]:
np.intersect1d(a, b)

array([2, 3])

In [150]:
np.setdiff1d(a, b)

array([1])

In [151]:
np.setdiff1d(b, a)

array([4, 5, 6])

### Performance and vectorization

Numpy 등의 모듈은 내부적으로 FORTRAN, C, C++ 등의 컴파일된 언어를 이용하기 때문에 매우 빠르다.  
다음의 두 코드를 비교했을 때, 같은 기능이지만 두 번째 코드가 훨씬 빠르다.

In [152]:
%%timeit
v = np.arange(10)
w = np.zeros((10,))
for i in np.arange(len(v)):
    w[i] = v[i] + 5
w

3.36 µs ± 12.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [153]:
%%timeit
w = v + 5
w

698 ns ± 2.49 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


```vectorize```를 이용하는 것이 빠르다.

In [154]:
def my_func(x):
    y = x**3 - 2*x + 5
    if y>0.5:
        return y-0.5
    else:
        return 0

In [155]:
%%timeit
[my_func(vk) for vk in v]

21.4 µs ± 62 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [156]:
%%timeit
np.vectorize(my_func)(v)

11.6 µs ± 44.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Broadcasting

Numpy broadcasting의 핵심 개념은 두 개의 서로 다른, 하지만 호환 가능한 shape을 가지는 array들이 연산될 때, 이를 적절히 처리하는 능력이다.

벡터와 스칼라의 연산

In [157]:
vector = np.arange(4) # array([0.,1.,2.,3.])
vector + 1.  

array([1., 2., 3., 4.])

벡터와 행렬의 연산

In [158]:
M = np.array([[11, 12, 13, 14],
           [21, 22, 23, 24],
           [31, 32, 33, 34]])
v = np.array([100, 200, 300, 400])
M + v

array([[111, 212, 313, 414],
       [121, 222, 323, 424],
       [131, 232, 333, 434]])

서로 다른 shape을 가지는 column 행렬과 row 행렬 간의 연산

In [159]:
C = np.arange(3).reshape(-1,1) # column
C

array([[0],
       [1],
       [2]])

In [160]:
R = np.arange(2).reshape(1,-1) # row
R

array([[0, 1]])

In [161]:
C + R  

array([[0, 1],
       [1, 2],
       [2, 3]])

다른 예제

In [162]:
coeff = np.array([-1,-2,-3]).reshape(-1,1)
M * coeff

array([[ -11,  -12,  -13,  -14],
       [ -42,  -44,  -46,  -48],
       [ -93,  -96,  -99, -102]])

In [163]:
coeff = np.array([-1,-2,-3,-4])

M * coeff

array([[ -11,  -24,  -39,  -56],
       [ -21,  -44,  -69,  -96],
       [ -31,  -64,  -99, -136]])

In [164]:
u = np.array([1, 2])
v = np.array([1, 2, 3])
W = u.reshape(-1,1) + v
W

array([[2, 3, 4],
       [3, 4, 5]])

### Meshgrid

```ogrid```는 open grid의 약자로 meshgrid를 생성한다.

아래에서 stride parameter로 ```3j```, 즉, 복소수를 사용하는데, 이는 step size가 아닌 number of step임을 뜻한다.

In [165]:
x,y = np.ogrid[0:1:3j,0:1:3j]  # x,y = ogrid[0:1.5:0.5, 0:1.5:0.5]와 동일

In [166]:
x

array([[0. ],
       [0.5],
       [1. ]])

In [167]:
y

array([[0. , 0.5, 1. ]])

이 meshgrid를 이용하여 two-dimensional function을 evaluation할 수 있다.

In [168]:
w = np.cos(x) + np.sin(2*y)
w

array([[1.        , 1.84147098, 1.90929743],
       [0.87758256, 1.71905355, 1.78687999],
       [0.54030231, 1.38177329, 1.44959973]])

```meshgrid``` 함수 또한 많이 이용된다.

In [169]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)

In [170]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [171]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [172]:
Z = (X + Y) ** 2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])